server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: m010203
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

